### PR TITLE
Initial PR/commit. Set up dependencies.

### PR DESCRIPTION
**Pull request by catslanderer**

### CODE REVIEW

**Review by wandadotdev — COMMENTED** [review]
Nope, you didn't break the rules at all.

**Review by wandadotdev — COMMENTED** [review]
Implementing get_max() with recursion is very impressive.

**Comment by derpwanda** [comment]
Glad to see you are feeling good and ahead of the game this week, Chris.

**Comment by wandadotdev** [comment]
Awesome job this week, Chris. Congrats on getting the AVL Tree completed.

**Pull request merged**
